# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    wget https://github.com/zegl/kube-score/releases/download/v1.15.0/kube-score_1.15.0_linux_amd64.tar.gz
    tar -xvzf ./kube-score_1.15.0_linux_amd64.tar.gz
    echo current working directory
    pwd
    echo list directory
    ls
    cd manifests
    ls
   
  displayName: 'Download kube-score package'
- script:  
    $(Agent.BuildDirectory)/s/kube-score score *.yaml
  displayName: 'Analyze with kube-score'
